Feature 210/redo database schema
UTDallasEPICS/Wellness-Center-Older-Adults pull request #228
Opened 2024-11-12 05:41 UTC by aaryaamoharir

2024-11-13 22:32 UTC, devAgant commented on app/api/createCustomerAccount/route.ts
> -      customerEmail,
please remove the unneeded GPT comments

2024-11-13 22:39 UTC, devAgant requested changes

2024-11-13 22:39 UTC, devAgant commented on prisma/schema.prisma
>    time DateTime @db.Time(4)
If this is what I think it is supposed to be, the name of this needs to be changed to something like 'rideDuration'. Unless this is something else?

2024-11-13 22:55 UTC, devAgant requested changes

2024-11-13 22:55 UTC, devAgant commented on prisma/schema.prisma
Customer Model Missing zipcode and RideIDArray fields

2024-11-13 22:55 UTC, devAgant commented on prisma/schema.prisma
> +  //volunteers is referenced by employee
Why is volunteer referenced by employee?

2024-11-13 22:55 UTC, devAgant commented on prisma/schema.prisma
> +  volunteers    Volunteer[] // Relation to Volunteer (One Employee to Many Volunteers)
Do the employees need a relation to volunteer? (While they may have a relationship in the real world, do they have a relationship within the scope of our application?)

2024-11-13 22:55 UTC, devAgant commented on prisma/schema.prisma
> +  employeesHandled Employee[] // Relation to Employee (One Admin to Many Employees)
The admin is missing a direct reference to volunteers right now. This is not good because if  the employee model is modified, then admin also loses its reference to volunteers.

2024-11-13 22:55 UTC, devAgant commented on app/api/createRide/route.ts
If you are fixing the createRide route, consider fixing the middleware and authentication routes so that the User table can be removed as well.

2024-11-14 03:14 UTC, aaryaamoharir commented on prisma/schema.prisma
> +  //volunteers is referenced by employee
It's storing the volunteers that the employees are watching over and I think we included it in the wiki with the database schema so I added it in the schema

2024-11-14 03:18 UTC, aaryaamoharir commented on prisma/schema.prisma
>    time DateTime @db.Time(4)
it was there from before so I just kept it but adding in a rideDuration field might make sense or a rideStartTime and rideEndTime and the date field is for what date the ride is occurring

2024-11-14 03:25 UTC, aaryaamoharir commented on prisma/schema.prisma
> +  volunteers    Volunteer[] // Relation to Volunteer (One Employee to Many Volunteers)
i think we decided to leave it on there so that the employees are connected to certain volunteers but honestly idk if the wellness center really needs that.

2024-11-14 22:13 UTC, CalvinVan approved these changes

2024-11-14 22:22 UTC, devAgant approved these changes

2024-11-14 23:34 UTC, merged